### ISSUE TITLE
User management | View user | Missing the fields according to document

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#110]
![Screenshot_2022-11-21_18-15-56](https://user-images.githubusercontent.com/58418713/203058759-e468529f-7f52-4655-99ed-58048a7605fd.png)

**Comment by rgnarok** [comment]
@atul-gautam-au6  details are not coming up
<img width="822" alt="image" src="https://user-images.githubusercontent.com/85341053/203765246-395be6c7-ff24-442c-8c56-cdcb711b2da2.png">
IT is defined in the document but fields are not coming client asks to showcase this irrespective of value is there or not the same case for other fields
<img width="712" alt="image" src="https://user-images.githubusercontent.com/85341053/203765455-ab564600-897f-4193-814f-ecc559a2f8ed.png">
<img width="833" alt="image" src="https://user-images.githubusercontent.com/85341053/203765507-0813d2c9-c6cc-4a3e-9ffc-457f9b51c909.png">

**Comment by atul-gautam-au6** [comment]
![Uploading Screenshot_2022-11-24_18-12-05.png…]()

**Comment by atul-gautam-au6** [comment]
![Uploading Screenshot_2022-11-24_18-13-43.png…]()

**Comment by atul-gautam-au6** [comment]
![Screenshot_2022-11-25_09-24-18](https://user-images.githubusercontent.com/58418713/203898132-71473e95-f8fd-4fb6-82c2-d9379f19a2ec.png)

**Comment by atul-gautam-au6** [comment]
![Screenshot_2022-11-25_09-25-02](https://user-images.githubusercontent.com/58418713/203898217-8ffef06f-04cc-435a-ae93-afa126fc8cf0.png)
![Screenshot_2022-11-25_09-24-53](https://user-images.githubusercontent.com/58418713/203898222-8d6b2734-63c7-4216-bbb4-aa68ccd25e54.png)

**Comment by atul-gautam-au6** [comment]
@rgnarok
