### ISSUE TITLE
Master setting

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#16]
Option to add in bulk is not added

**Comment by rgnarok** [comment]
@atul-gautam-au6  please add a sample to see for the user to check what type of format they need to upload in CSV

**Comment by atul-gautam-au6** [comment]
[location.csv](https://github.com/atul-gautam-au6/THIP-Issue-tracker/files/9533098/location.csv)
[history.csv](https://github.com/atul-gautam-au6/THIP-Issue-tracker/files/9533099/history.csv)
[category.csv](https://github.com/atul-gautam-au6/THIP-Issue-tracker/files/9533100/category.csv)
@rgnarok please use this type of format

**Comment by rgnarok** [comment]
@atul-gautam-au6  i am saying add a sample for user on the admin so that he understands this

**Comment by atul-gautam-au6** [comment]
@rgnarok ok
