### ISSUE TITLE
Blog pointers

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#206]
1. Check Ui properly. Minor things like the curve  in the image is missing

2.  The transition is no way like InShorts. Fix transition.
 No need to show Author (label and name)

3. For body text use the CSS (font size, style and colour) of the label Author Name.

4. Remove Dropcase (first letter big) from body text
 
5. Call data only where short answer OR body text is present

6. Category is not to be displayed. It should be Health Conditions or Treatment 

7. Why is only 20 articles called? It should continue to show all data.

8. The "Swipe left for detailed answer" text is missing (check InShorts)

9. The alternate question at bottom is missing (check Figma for "Next:" )

**Comment by abdulkhira1** [comment]
@rgnarok pls attack screenshot

**Comment by abdulkhira1** [comment]
> * Call data only where short answer OR body text is present
> *

this pointer needs to done from api side

**Comment by abdulkhira1** [comment]
@rgnarok transition created similar inshort check and comment here

**Comment by rgnarok** [comment]
@abdulkhira1  transition is still not similar it is the opposite of what is going on the in inshorts

**Comment by abdulkhira1** [comment]
#231 duplicate
