### ISSUE TITLE
Add appointment >> Slots are not coming up to select 

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#213]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/85341053/212678250-9179e6eb-0612-4e8d-abdf-1fb92b423be1.png">

**Comment by atul-gautam-au6** [comment]
@rgnarok slots are dynamic that  come from backend based on doctor

**Comment by atul-gautam-au6** [comment]
please let me know what is the issue..?
