### ISSUE TITLE
Dosha profile >> Questions

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#226]
When I select 1 option and the process continues and comes back the selected answer disappears. It is not maintaining the state please fix

**Comment by abdulkhira1** [comment]
@rgnarok when you click on continue it's store your answer in database

**Comment by rgnarok** [comment]
@abdulkhira1  it must show the selected option when i press back please fix it is the flow as per experience it is not re evaluation it is going to back of what is selected
