### ISSUE TITLE
Add doctor >> Add option to add speciality and gender in the add and edit form 

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#249]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/85341053/213410535-64a15cbd-b6e9-459a-909d-857cf635148b.png">

**Comment by atul-gautam-au6** [comment]
@rgnarok please update on doc also

**Comment by VinayChaurasiya96** [comment]
@atul-gautam-au6  need api changes
