### ISSUE TITLE
Podcast >> No result illustration is missing

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#277]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/85341053/215457002-9cce9aa9-4af1-4929-9b2f-9894ecce387d.png">

**Comment by atul-gautam-au6** [comment]
its working @rgnarok 
![Screenshot_2023-02-03_13-52-42](https://user-images.githubusercontent.com/58418713/216548905-1b04f194-fb83-403b-83a7-5c51990b6163.png)
