### ISSUE TITLE
Sign in > The Images should cover till the screen edges.

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#29]
![Screenshot_20220909-111930_2](https://user-images.githubusercontent.com/93506258/189281275-1a80ebb9-a60a-4079-b8eb-eac7ce3179a0.png)

**Comment by rohitrvayuz** [comment]
This is working

**Comment by Mehulna** [comment]
@rohitrvayuz in my phone still its showing.
