### ISSUE TITLE
Onboarding screen.

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#31]
**### Can we go with the White background. It looks good and clear images are also visible.**

![Onboarding- Personal Doctors are Just a Call Away](https://user-images.githubusercontent.com/93506258/189282038-fe7ee446-9eb1-4dc7-8c0e-450bd18b97a0.jpg)
![Screenshot_20220909-111907 (1)](https://user-images.githubusercontent.com/93506258/189282047-2c8024dc-39de-4fa4-b13d-c639075668b2.png)

**Comment by rgnarok** [comment]
@Mehulna  sure

**Comment by Mehulna** [comment]
@rohitrvayuz  sir please change this screens to white Bg.
