### ISSUE TITLE
 The "Upload Document" is not working [ Insurance, Invoice, Prescription, ]. Please fix that. It was working fine earlier.

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#320]

**Comment by ShikharVayuz** [comment]
@rgnarok Please let me know when you saw this working last because if we are talking about this screen
![image](https://user-images.githubusercontent.com/86296418/218749726-f6c410c0-6b03-4444-b2df-5b0ffcd8276f.png)
The screens for My Insurance, Invoice and Presciption has not been made.

**Comment by rgnarok** [comment]
@ShikharVayuz  please close this this has same flow as we have in my reports we need to give option to upload and show them like the flow we have in my medical reports

**Comment by ShikharVayuz** [comment]
@rgnarok Please check these issues before reporting and mention the cases along with those this leads to the wrong information being shared.

**Comment by ShikharVayuz** [comment]
@atul-gautam-au6 Please create the api for the same
