### ISSUE TITLE
The final ABHA card page design [currently linked from Documents] is wrong. It is NOT same as success notification page design.

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#343]

**Comment by rgnarok** [comment]
<img width="225" alt="image" src="https://user-images.githubusercontent.com/85341053/220077369-f92e4647-52b6-4978-ab2c-290379d64e12.png">

@abdulkhira1  this is the design we need to follow for the document screen
