### ISSUE TITLE
Verify Details Page - Design still not proper. Background to alternate number still missing? Why is this happening?

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#345]

**Comment by abdulkhira1** [comment]
@atul-gautam-au6  @rgnarok attach screenshot

**Comment by atul-gautam-au6** [comment]
![Screenshot_20230220_121800.jpg](https://user-images.githubusercontent.com/58418713/220033268-6c2ded23-3277-4af5-9878-b7b30a71b6dd.jpg)
