### ISSUE TITLE
Enter Aadhaar Number - Remove phone number from that page.

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#349]

**Comment by abdulkhira1** [comment]
@atul-gautam-au6 @rgnarok attach screenshot

**Comment by atul-gautam-au6** [comment]
[![Screenshot_20230220_121925.jpg](https://user-images.githubusercontent.com/58418713/220033563-b7ae65f5-1620-488c-a7f0-119bff931750.jpg)
