### ISSUE TITLE
Create ABHA Profile page (when user choosing ABHA address) – Why is the design, text, label – all different in this page than what is given in Figma?

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#354]

**Comment by abdulkhira1** [comment]
@rgnarok we don't have existing abha id api 
will show exsting abha id design when we have api

**Comment by rgnarok** [comment]
1. Correct the heading it does not create Abha profile it is select Abha address
2. It should be pre-fill like we have when we are creating it Abha using aadhaar flow
