### ISSUE TITLE
App  >> Doctor >> Book appointment

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#364]
when i select any doctor > description > book appointment >> doctor field need to update automatic

**Comment by atul-gautam-au6** [comment]
@ShikharVayuz when book appointment through doctor profile doctor should auto selected with current doctor profile but its showing select doctor

**Comment by rgnarok** [comment]
@atul-gautam-au6  check and close
