### ISSUE TITLE
Required API's For Following -> My Insurance, My Prescription, My Invoice

### ISSUE THREAD

**Issue by ShikharVayuz** [atul-gautam-au6/THIP-Issue-tracker#385]
![image](https://user-images.githubusercontent.com/86296418/222639229-31d9a9ab-6328-4ee7-8ef5-2002f286b345.png)

**Comment by atul-gautam-au6** [comment]
@ShikharVayuz @rgnarok  what is my invoice and my insurance ..?

**Comment by rgnarok** [comment]
@atul-gautam-au6  it will be same as we are uploading the documents in my medical reports

**Comment by atul-gautam-au6** [comment]
@ShikharVayuz updated prescription api > /user/appointments/doctor/prescription  >>https://thip.care/api#/user-prescription-list/UserAppointmentController_getPrescriptionList
