### ISSUE TITLE
difficult to understand is it slider or not. use one more card beside that in light.

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#39]
![WhatsApp Image 2022-09-27 at 12 18 58 PM (2)](https://user-images.githubusercontent.com/93506258/192454977-6e010215-d1dd-4053-9742-9b18f8a34ee9.jpeg)

**Comment by rohitrvayuz** [comment]
Ok. Will decrease the width
