### ISSUE TITLE
Requirement of Notification Trigger Sheet

### ISSUE THREAD

**Issue by ShikharVayuz** [atul-gautam-au6/THIP-Issue-tracker#404]

**Comment by ShikharVayuz** [comment]
https://docs.google.com/spreadsheets/d/1vJMu1UziIp3YI2P0bSGDWJqoA3DE7WGq3tt79G3SzMg/edit?usp=sharing

**Comment by ShikharVayuz** [comment]
@atul-gautam-au6 Please mention NOTIFICATION_TRIGGER keys aswell.

**Comment by rgnarok** [comment]
@abdulkhira1  what is needed here?
