### ISSUE TITLE
Illustration is breaking please fix this

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#412]
![MicrosoftTeams-image - 2023-03-27T160513 505](https://user-images.githubusercontent.com/93506258/227917901-7a0090f6-cd98-4385-9171-0276f3704105.png)

**Comment by ShikharVayuz** [comment]
![image](https://user-images.githubusercontent.com/86296418/228114834-f00241c9-fc6f-499f-ad53-930f005560fc.png)
