### ISSUE TITLE
Card Layout is different from Figma.

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#415]
![MicrosoftTeams-image - 2023-03-27T161901 654](https://user-images.githubusercontent.com/93506258/227920969-d24391b4-7886-42ba-a2a2-2c98c6500586.png)

**Comment by ShikharVayuz** [comment]
![image](https://user-images.githubusercontent.com/86296418/228116736-c0284107-77d6-47bc-aac9-a8d4cd0e86e5.png)
![image](https://user-images.githubusercontent.com/86296418/228116799-26d12561-7897-4399-816b-0d31cde98a9b.png)

**Comment by ShikharVayuz** [comment]
What part is different @Mehulna

**Comment by Mehulna** [comment]
Make card as it is in Articles @ShikharVayuz
