### ISSUE TITLE
check the font weight in figma, not looking same

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#42]
![44a7d7cf-d194-4187-b828-3c40d15842c2](https://user-images.githubusercontent.com/93506258/192458879-ab7c96fe-c6fd-4300-9c25-6e2f0734133a.jpg)

**Comment by rohitrvayuz** [comment]
@Mehulna  Please check if we want two different font family for the app since the starting screens have a different font than this
