### ISSUE TITLE
Lifestyle Habits UI is not same as figma

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#426]
![MicrosoftTeams-image - 2023-03-27T165059 301](https://user-images.githubusercontent.com/93506258/227927506-7bdb2dce-7e34-4aef-9c81-8bb8591f359c.png)

**Comment by ShikharVayuz** [comment]
![image](https://user-images.githubusercontent.com/86296418/228124336-7953a877-d46e-4584-ad5f-9eb571c31ece.png)
![image](https://user-images.githubusercontent.com/86296418/228124379-6101eedd-b9e3-4a5f-bc12-a002b673a498.png)
