### ISSUE TITLE
Deactivate Continue button unless its selected.

### ISSUE THREAD

**Issue by Mehulna** [atul-gautam-au6/THIP-Issue-tracker#428]
![MicrosoftTeams-image - 2023-03-27T165827 241](https://user-images.githubusercontent.com/93506258/227929186-904f9381-faf2-4f43-8dc9-4f6edb6a6498.png)

**Comment by ShikharVayuz** [comment]
@Mehulna We already have text in there so I dont see a point in making it inactive.

**Comment by abdulkhira1** [comment]
@Mehulna field is not mandatory
