### ISSUE TITLE
App logo

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#45]
Add app logo instead of flutter logo please fix

**Comment by rohitrvayuz** [comment]
@Mehulna  Please share App Logo for Play Store and App Store.

**Comment by Mehulna** [comment]
Ok @rohitrvayuz

**Comment by Mehulna** [comment]
![Group 18712](https://user-images.githubusercontent.com/93506258/196611367-ee2f01b9-c5bb-447b-b53e-c0f6053eb68a.png)

**Comment by Mehulna** [comment]
@rohitrvayuz 512 X512

**Comment by Mehulna** [comment]
![Group 18712 (2)](https://user-images.githubusercontent.com/93506258/196670576-3cbd2ac7-42ed-459f-b5d5-54e361b2355a.png)


@rohitrvayuz
