### ISSUE TITLE
Admin > Community > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [atul-gautam-au6/THIP-Issue-tracker#557]
![image](https://github.com/atul-gautam-au6/THIP-Issue-tracker/assets/129847373/593e9dac-4f6b-447f-a4b4-91b0632c3db8)
While adding the community , if there is a validation for not accepting details atleast it  should be displayed what needs to be filled correctly

**Comment by atul-gautam-au6** [comment]
@rajasrivastava101 pls upload screenshot
