### ISSUE TITLE
User View Api is Not giving Required data 

### ISSUE THREAD

**Issue by SyedSameer826** [atul-gautam-au6/THIP-Issue-tracker#60]
https://thip-server.herokuapp.com/admin/user/userDetails/634d4124a6da9a470aa91da1
![image](https://user-images.githubusercontent.com/87633728/198587096-0cf56768-afc7-4f3c-b272-70f5431dc761.png)

**Comment by atul-gautam-au6** [comment]
@SyedSameer826 is it fixed
