### ISSUE TITLE
Podcast | Manage podcast track

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#62]
- [x] 2. Add status and manage the status
- [x] Edit is not working
- [x] Add is not working
- [x] Edit/Add cancel button redirect is wrong
- [ ] admin can add multiple podcast track on add time | implement this functionality

**Comment by SyedSameer826** [comment]
Please Update the Change Status Api of Manage Podcast Track.
@atul-gautam-au6 @Ahlam000

**Comment by SyedSameer826** [comment]
@atul-gautam-au6,need API for  "admin can add multiple podcast track on add time | implement this functionality" point

**Comment by SyedSameer826** [comment]
as Discussed with @atul-gautam-au6 ,'admin can add multiple podcast track on add time | implement this functionality' this functionality is no more required in the application.
