### ISSUE TITLE
APP | General

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#67]
is it posspible if error is occurred then this will point to specific filed...?
![WhatsApp Image 2022-10-31 at 2 55 47 PM](https://user-images.githubusercontent.com/58418713/198975432-aee79615-fe59-4b9f-be05-a8f333e5a24d.jpeg)

**Comment by rohitrvayuz** [comment]
> is it posspible if error is occurred then this will point to specific filed...?

Yes, but you will need to send the key names from the API
