### ISSUE TITLE
App signin | not able to signin

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#69]

**Comment by atul-gautam-au6** [comment]
![Uploading WhatsApp Image 2022-10-31 at 3.01.25 PM.jpeg…]()

**Comment by rohitrvayuz** [comment]
[15:09] Rohit Rajput
503 error

[15:09] Rohit Rajput
<!DOCTYPE html>     <html>       <head>         <meta name="viewport" content="width=device-width, initial-scale=1">         <meta charset="utf-8">         <title>Application Error</title>         <style media="screen">           html,body,iframe {             margin: 0;             padding: 0;           }           html,body {             height: 100%;             overflow: hidden;           }           iframe {             width: 100%;             height: 100%;             border: 0;           }         </style>       </head>       <body>         <iframe src="//[www.herokucdn.com/error-pages/application-error.html"](https://www.herokucdn.com/error-pages/application-error.html%22)></iframe>

[15:09] Rohit Rajput
check server
