### ISSUE TITLE
App | Upload reports

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#71]
- [ ] 
![WhatsApp Image 2022-10-31 at 3 19 00 PM](https://user-images.githubusercontent.com/58418713/198980166-d5dee3ee-6e12-423a-980c-676de2b9c5d6.jpeg)
Via gallary is not working 
Download is not working

**Comment by rohitrvayuz** [comment]
> * [ ]
>   ![WhatsApp Image 2022-10-31 at 3 19 00 PM](https://user-images.githubusercontent.com/58418713/198980166-d5dee3ee-6e12-423a-980c-676de2b9c5d6.jpeg)
>   Via gallary is not working
>   Download is not working

Please send device details

**Comment by atul-gautam-au6** [comment]
Android 12  vivo V23 mobile
