### ISSUE TITLE
App | General | Auth

### ISSUE THREAD

**Issue by atul-gautam-au6** [atul-gautam-au6/THIP-Issue-tracker#73]
- [ ] where is showing my emergency contact
- [ ] How to update Medical profile
- [ ] How to map relation
- [ ] In menu drawer every module are same expect  Profile  section

**Comment by rohitrvayuz** [comment]
> * [ ]  where is showing my emergency contact
No screen for this as of now.
> * [ ]  How to update Medical profile
Go to menu
Then profile
Then edit profile
Then edit medical profile

> * [ ]  How to map relation
No screen for this. @Mehulna needs to create one

> * [ ]  In menu drawer every module are same expect  Profile  section
Only the modules for current sprint are targeted.
