### ISSUE TITLE
Homepage | Change the default image and use something which can be used by every user not this one

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#79]
![image](https://user-images.githubusercontent.com/85341053/199220384-1d81dbea-1d36-493f-b915-bed33965da18.png)

**Comment by rohitrvayuz** [comment]
Please ask for AWS from the client

**Comment by rohitrvayuz** [comment]
@Mehulna ?

**Comment by Mehulna** [comment]
Sharing @rohitrvayuz

**Comment by Mehulna** [comment]
![person](https://user-images.githubusercontent.com/93506258/199481819-c98923fe-f5ef-4a8a-9eb5-555b6a493c38.png)

**Comment by Mehulna** [comment]
@rohitrvayuz  ji check
