### ISSUE TITLE
add user

### ISSUE THREAD

**Issue by rgnarok** [atul-gautam-au6/THIP-Issue-tracker#8]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/184837495-e2e88232-a46e-4431-b320-9ac7db26d34a.png">
Validation added in the foundation docs are not added ex, i can add a numerical name for the user which should not be the case 
Please recheck and close the issue
No check of mobile, i can add any digit number and it is allowing me to add alphabetes

**Comment by rgnarok** [comment]
@atul-gautam-au6  add error message on the form itself for invalid email or name don't make me write the text and click on submit to make it work and check error are handled correctly or not

**Comment by rgnarok** [comment]
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/85341053/189292576-6a85897f-3e17-49c8-8d10-dec0b3d381a3.png">
I can add 2 user with same email please add this check kush11@mailinator.com

**Comment by atul-gautam-au6** [comment]
kush11@mailinator.com
 Kush11@mailinator.com 
@rgnarok this is not same email please recheck
