### ISSUE TITLE
Language choice screens need to be ready

### ISSUE THREAD

**Issue by senguptasudipta** [atul-gautam-au6/THIP-Issue-tracker#86]
Need Language Choose Screen Ready. They are the first screen of the app. [even before Sign In / Registration]

- Choose Primary Language
- Choose Secondary Language (Option: English and HIndi only)

Save language preference against each user ( one is primary language, another is secondary language)

**Comment by rohitrvayuz** [comment]
![Screenshot_1668057485](https://user-images.githubusercontent.com/78350161/201006928-2593bdfa-0d94-45cb-8c97-30963c591d18.png)

**Comment by rohitrvayuz** [comment]
We will be saving it during signup and settings for later

**Comment by rohitrvayuz** [comment]
![Screenshot_1668058097](https://user-images.githubusercontent.com/78350161/201008156-6961c8af-ab25-4462-ba35-659ebed2e5e9.png)

**Comment by rohitrvayuz** [comment]
![Screenshot_1668058097](https://user-images.githubusercontent.com/78350161/201008198-45a8d8a2-7377-465d-90c9-32de93219feb.png)

**Comment by rohitrvayuz** [comment]
screens and apis done
