### ISSUE TITLE
Social Media Login 

### ISSUE THREAD

**Issue by senguptasudipta** [atul-gautam-au6/THIP-Issue-tracker#87]
Need the following options in the registration page:

- Login by Facebook [Doesn't require email ID to be verified + Profile details can be pulled ]
- Login by Truecaller [ Doesn't require mobile number to be verified ]

**Comment by rohitrvayuz** [comment]
Truecaller only supports Android only right now for Flutter.

**Comment by senguptasudipta** [comment]
Perfectly fine. Go ahead with android only

**Comment by rohitrvayuz** [comment]
![Screenshot_1668055977](https://user-images.githubusercontent.com/78350161/201003788-c3aded4f-e377-4be1-b3fd-1f789aa543fe.png)
<img width="458" alt="Screenshot 2022-11-10 at 10 19 22" src="https://user-images.githubusercontent.com/78350161/201003808-2b4ded0a-60b1-440f-a510-9a9e32893829.png">

**Comment by rohitrvayuz** [comment]
Working for this solution.

**Comment by rohitrvayuz** [comment]
Facebook is now working. Making necessary changes to the Api according to the registration flow

**Comment by rohitrvayuz** [comment]
All social logins removed except Truecaller
