### ISSUE TITLE
Upload Report Not working

### ISSUE THREAD

**Issue by senguptasudipta** [atul-gautam-au6/THIP-Issue-tracker#90]
Upload medical report is not working. It keeps on showing an error - "Report Upload Error. Please try again"

Need the following modifications - 

1. Options should be Camera, Gallery and File. Whatsapp upload and Email Upload should also stay.
2. All options should WORK

**Comment by rohitrvayuz** [comment]
@atul-gautam-au6 Please share AWS details as soon as it is done

**Comment by senguptasudipta** [comment]
Shared over mail on 9th October.
Reshared on 8th November.

What details is missing?
