### ISSUE TITLE
 Upload Email - domain wrongly mapped

### ISSUE THREAD

**Issue by senguptasudipta** [atul-gautam-au6/THIP-Issue-tracker#91]
The domain from upload via mail where we give virtual email IDs to all users - the domain is wrong.

www.thip.care is the domain

Currently any report by mail gets a bounce back. Fix the domain and make the functionality WORK.

**Comment by rohitrvayuz** [comment]
@atul-gautam-au6 After uploading to the email it does not show up on the list.

**Comment by rohitrvayuz** [comment]
Done from front-end
