### ISSUE TITLE
ABHA Registration Functionality missing

### ISSUE THREAD

**Issue by senguptasudipta** [atul-gautam-au6/THIP-Issue-tracker#94]
Create my ABHA ID should come as a checkbox in first registration (mobile number) input screen. [ Refer to #88 ]
OTP should go from ABHA for mobile verification is checkbox is checked
Next screen should have ABHA ID creation [<ID input field>@abdm]
Post that, registration flow should continue as it is.

[This is NOT full ABHA integration. This is just ABHA registration API]

**Comment by rohitrvayuz** [comment]
@atul-gautam-au6  Please update here when done.

**Comment by rohitrvayuz** [comment]
UI is done
@atul-gautam-au6  please share collection here

**Comment by rohitrvayuz** [comment]
duplicate of #88
